---
- name: Ensure MariaDB server is installed
  ansible.builtin.package:
    name: mariadb-server
    state: present

- name: Ensure MariaDB is started and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
