---
- name: Configure firewalld on all servers
  hosts: all
  become: true
  tasks: 
    - name: Ensure firewalld and python3-firewall are installed
      ansible.builtin.package: 
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Ensure firewalld is started and enabled
      ansible.builtin.service:
        name: firewalld
        state: started 
        enabled: true

- name: Configure webserver firewall
  hosts: web  
  become: true
  tasks:
    - name: Allow HTTP and HTTPS through firewalld
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        state: enabled
        immediate: true
      loop:
        - http
        - https

- name: Configure dbserver firewall
  hosts: db
  become: true
  tasks:
    - name: Allow MYSQL through firewalld
      ansible.posix.firewalld:
        service: mysql
        permanent: true
        state: enabled
        immediate: true
